import axios from 'axios'

/* Slacker

   This is a basic logger module that can be used to send various log messages
   to slack and to the local console. It relies on the SLACK_HOOK environment
   variable to proivude the URL to post the message to.

   All messages will also be printed to stderr/stdout via the console.

   The slack URL itself can be generated by creating an application and an
   associated Incoming Webhook.

*/

// Format a message as an error to be sent to slack
function formatError (error) {
  return {
    mkdwn: true,
    attachments: [{
      title: 'Error',
      color: '#f50057',
      text: error
    }]
  }
}

// Format a message as an error to be sent to slack
function formatWarn (log) {
  return {
    mkdwn: true,
    attachments: [{
      title: 'Warning',
      color: '#ffdd33',
      text: log
    }]
  }
}

// Format a message as a normal log to be sent to slack
function formatInfo (log) {
  return {
    mkdwn: true,
    attachments: [{
      color: 'good',
      text: log
    }]
  }
};

// Format a debug message to be sent to slack
function formatDebug (log) {
  return {
    mkdwn: true,
    attachments: [{
      title: 'Debug',
      color: '#BBBBBB',
      text: log
    }]
  }
};

// Send a message to slack
async function notify (msg) {
  if (typeof (msg) !== 'undefined' && process.env.SLACK_HOOK && process.env.SLACK_LOG !== 'false') {
    return axios.post(process.env.SLACK_HOOK, msg)
      .catch(err => console.error(`Error: slacker.notify unable to log message: ${msg}: ${err}`))
  }
}

/// ////////////////////////////////////////////////////////////////////////////
// Exported logging functionality

const logger = {}

// Send an error message to slack
logger.error = async log => {
  console.error(`Error: ${log}`)
  return notify(formatError(log))
}

// Send a warning message to slack
logger.warn = async log => {
  console.warn(`Warn:  ${log}`)
  return notify(formatWarn(log))
}

// Send an information message to slack
logger.info = async log => {
  console.info(`Info:  ${log}`)
  return notify(formatInfo(log)).catch(err => console.error(`Error: logger.info: { ${err}, ${log} }`))
}

// Send an debug message to slack
logger.debug = async log => {
  console.debug(`Debug: ${log}`)
  return notify(formatDebug(log)).catch(err => console.error(`Error: logger.debug: { ${err}, ${log} }`))
}

export { logger }
